const { fontFamily } = require('tailwindcss/defaultTheme')

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['selector', '[data-theme="dark"]'],
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['DM Sans', ...fontFamily.sans],
        mono: ['DM Mono', 'Fira Code', ...fontFamily.mono],
      },
      colors: {
        'bg-app':              'var(--color-bg-app)',
        'bg-surface':          'var(--color-bg-surface)',
        'bg-surface-raised':   'var(--color-bg-surface-raised)',
        'bg-subtle':           'var(--color-bg-subtle)',
        'bg-inverse':          'var(--color-bg-inverse)',
        'text-primary':        'var(--color-text-primary)',
        'text-secondary':      'var(--color-text-secondary)',
        'text-placeholder':    'var(--color-text-placeholder)',
        'text-disabled':       'var(--color-text-disabled)',
        'text-inverse':        'var(--color-text-inverse)',
        'text-link':           'var(--color-text-link)',
        'border-default':      'var(--color-border-default)',
        'border-strong':       'var(--color-border-strong)',
        'border-focus':        'var(--color-border-focus)',
        'border-error':        'var(--color-border-error)',
        'action-primary':      'var(--color-action-primary)',
        'action-primary-hover':'var(--color-action-primary-hover)',
        'action-primary-text': 'var(--color-action-primary-text)',
        'action-secondary':    'var(--color-action-secondary)',
        'action-secondary-border': 'var(--color-action-secondary-border)',
        'action-secondary-hover':  'var(--color-action-secondary-hover)',
        'positive':            'var(--color-positive)',
        'positive-subtle':     'var(--color-positive-subtle)',
        'negative':            'var(--color-negative)',
        'negative-subtle':     'var(--color-negative-subtle)',
        'warning':             'var(--color-warning)',
        'warning-subtle':      'var(--color-warning-subtle)',
        'info':                'var(--color-info)',
        'info-subtle':         'var(--color-info-subtle)',
      },
      boxShadow: {
        '1': 'var(--shadow-1)',
        '2': 'var(--shadow-2)',
        '3': 'var(--shadow-3)',
        '4': 'var(--shadow-4)',
      },
      borderRadius: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '24px',
        'pill': '9999px',
      },
      fontSize: {
        'xs':   ['11px', { lineHeight: '16px', letterSpacing: '0.02em' }],
        'sm':   ['12px', { lineHeight: '18px' }],
        'base': ['14px', { lineHeight: '22px' }],
        'md':   ['16px', { lineHeight: '24px', letterSpacing: '-0.01em' }],
        'lg':   ['20px', { lineHeight: '28px', letterSpacing: '-0.02em' }],
        'xl':   ['24px', { lineHeight: '32px', letterSpacing: '-0.02em' }],
        '2xl':  ['30px', { lineHeight: '38px', letterSpacing: '-0.03em' }],
        '3xl':  ['38px', { lineHeight: '46px', letterSpacing: '-0.03em' }],
      },
      transitionDuration: {
        'instant':    '80ms',
        'fast':       '150ms',
        'standard':   '220ms',
        'deliberate': '350ms',
      },
      transitionTimingFunction: {
        'standard':   'cubic-bezier(0.2, 0, 0, 1)',
        'decelerate': 'cubic-bezier(0, 0, 0.2, 1)',
        'accelerate': 'cubic-bezier(0.4, 0, 1, 1)',
      },
      spacing: {
        '1':  '4px',
        '2':  '8px',
        '3':  '12px',
        '4':  '16px',
        '5':  '20px',
        '6':  '24px',
        '8':  '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
      },
    },
  },
  plugins: [],
}
